#该文件中配置红包服务的测试环境配置数据
red:
  remark: '{cipher}AQCJL7QQ3487zGxsGFkWlTUPXvFq37dLK8M6tspM0ppWtcITJt7pzLFZ4vOsF4vMznJAsSWPVJz6ehHEBid6/74eTXYQEjSJYfCSMVqp/Y73Fh6EdPs4Kwpiiivl0MEwOjFLUKy6ZtMUnyRtJ+GDrQIFiuGNif/KWLJTyGA1QfDz1egsYJwZNSrIN6mECj5biFRZKsLs1oq4z+Ma4rIb7YJVYbTds01iQa138KPQYwAsKnGyLikOITi5vVwTLsXI3w0RtA7CqFB/9m/LVEKc7mWsMk7gOAt7CohdzT74yFiNLpce0sAulRfNCU/uyBTecyIAFiFpBo9je1u0qYRTEU2y6KcvUZsER9xnpbeXAJFucxAIpbETFujqsfvMutwuSEBN2S1lBizPOifWYuupXmUZ'

